USE [master]
GO

/****** Object:  Database [NodeJSTest]    Script Date: 28/02/2022 04:03:18 p. m. ******/
CREATE DATABASE [NodeJSTest] ON  PRIMARY 
( NAME = N'NodeJSTest', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL.1\MSSQL\DATA\NodeJSTest.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'NodeJSTest_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL.1\MSSQL\DATA\NodeJSTest_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

EXEC dbo.sp_dbcmptlevel @dbname=N'NodeJSTest', @new_cmptlevel=90
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NodeJSTest].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [NodeJSTest] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [NodeJSTest] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [NodeJSTest] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [NodeJSTest] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [NodeJSTest] SET ARITHABORT OFF 
GO

ALTER DATABASE [NodeJSTest] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [NodeJSTest] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [NodeJSTest] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [NodeJSTest] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [NodeJSTest] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [NodeJSTest] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [NodeJSTest] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [NodeJSTest] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [NodeJSTest] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [NodeJSTest] SET  DISABLE_BROKER 
GO

ALTER DATABASE [NodeJSTest] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [NodeJSTest] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [NodeJSTest] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [NodeJSTest] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [NodeJSTest] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [NodeJSTest] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [NodeJSTest] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [NodeJSTest] SET  MULTI_USER 
GO

ALTER DATABASE [NodeJSTest] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [NodeJSTest] SET DB_CHAINING OFF 
GO

ALTER DATABASE [NodeJSTest] SET  READ_WRITE 
GO


